const lesson3 = [
  { hanzi: "爱", pinyin: "ài", meaning: "yêu / thích", audio: "audio/lesson3/001.mp3" },
  { hanzi: "阿姨", pinyin: "āyí", meaning: "cô / dì", audio: "audio/lesson3/002.mp3" },
  { hanzi: "矮", pinyin: "ǎi", meaning: "thấp", audio: "audio/lesson3/003.mp3" },
  { hanzi: "爱好", pinyin: "àihào", meaning: "sở thích", audio: "audio/lesson3/004.mp3" },
  { hanzi: "安静", pinyin: "ānjìng", meaning: "yên tĩnh", audio: "audio/lesson3/005.mp3" },
  { hanzi: "把", pinyin: "bǎ", meaning: "đem / cầm / (trợ từ)", audio: "audio/lesson3/006.mp3" },
  { hanzi: "半", pinyin: "bàn", meaning: "nửa", audio: "audio/lesson3/007.mp3" },
  { hanzi: "班", pinyin: "bān", meaning: "lớp / ca", audio: "audio/lesson3/008.mp3" },
  { hanzi: "搬", pinyin: "bān", meaning: "chuyển / dời", audio: "audio/lesson3/009.mp3" },
  { hanzi: "办法", pinyin: "bànfǎ", meaning: "cách / phương pháp", audio: "audio/lesson3/010.mp3" },

  { hanzi: "办公室", pinyin: "bàngōngshì", meaning: "văn phòng", audio: "audio/lesson3/011.mp3" },
  { hanzi: "帮忙", pinyin: "bāngmáng", meaning: "giúp đỡ", audio: "audio/lesson3/012.mp3" },
  { hanzi: "饱", pinyin: "bǎo", meaning: "no", audio: "audio/lesson3/013.mp3" },
  { hanzi: "包", pinyin: "bāo", meaning: "túi / gói", audio: "audio/lesson3/014.mp3" },
  { hanzi: "被", pinyin: "bèi", meaning: "bị", audio: "audio/lesson3/015.mp3" },
  { hanzi: "北方", pinyin: "běifāng", meaning: "miền Bắc", audio: "audio/lesson3/016.mp3" },
  { hanzi: "笔记本", pinyin: "bǐjìběn", meaning: "vở / laptop", audio: "audio/lesson3/017.mp3" },
  { hanzi: "比较", pinyin: "bǐjiào", meaning: "tương đối / khá", audio: "audio/lesson3/018.mp3" },
  { hanzi: "比赛", pinyin: "bǐsài", meaning: "thi đấu", audio: "audio/lesson3/019.mp3" },
  { hanzi: "必须", pinyin: "bìxū", meaning: "phải / bắt buộc", audio: "audio/lesson3/020.mp3" },

  { hanzi: "鼻子", pinyin: "bízi", meaning: "mũi", audio: "audio/lesson3/021.mp3" },
  { hanzi: "变化", pinyin: "biànhuà", meaning: "thay đổi", audio: "audio/lesson3/022.mp3" },
  { hanzi: "别人", pinyin: "biérén", meaning: "người khác", audio: "audio/lesson3/023.mp3" },
  { hanzi: "冰箱", pinyin: "bīngxiāng", meaning: "tủ lạnh", audio: "audio/lesson3/024.mp3" },
  { hanzi: "不但…而且…", pinyin: "búdàn… érqiě…", meaning: "không những… mà còn…", audio: "audio/lesson3/025.mp3" },
  { hanzi: "菜单", pinyin: "càidān", meaning: "thực đơn", audio: "audio/lesson3/026.mp3" },
  { hanzi: "参加", pinyin: "cānjiā", meaning: "tham gia", audio: "audio/lesson3/027.mp3" },
  { hanzi: "草", pinyin: "cǎo", meaning: "cỏ", audio: "audio/lesson3/028.mp3" },
  { hanzi: "层", pinyin: "céng", meaning: "tầng", audio: "audio/lesson3/029.mp3" },
  { hanzi: "差", pinyin: "chà", meaning: "kém / thiếu", audio: "audio/lesson3/030.mp3" },

  { hanzi: "超市", pinyin: "chāoshì", meaning: "siêu thị", audio: "audio/lesson3/031.mp3" },
  { hanzi: "衬衫", pinyin: "chènshān", meaning: "áo sơ mi", audio: "audio/lesson3/032.mp3" },
  { hanzi: "成绩", pinyin: "chéngjì", meaning: "kết quả / điểm số", audio: "audio/lesson3/033.mp3" },
  { hanzi: "城市", pinyin: "chéngshì", meaning: "thành phố", audio: "audio/lesson3/034.mp3" },
  { hanzi: "迟到", pinyin: "chídào", meaning: "đến muộn", audio: "audio/lesson3/035.mp3" },
  { hanzi: "除了", pinyin: "chúle", meaning: "ngoài ra / trừ", audio: "audio/lesson3/036.mp3" },
  { hanzi: "船", pinyin: "chuán", meaning: "thuyền", audio: "audio/lesson3/037.mp3" },
  { hanzi: "春", pinyin: "chūn", meaning: "mùa xuân", audio: "audio/lesson3/038.mp3" },
  { hanzi: "词典", pinyin: "cídiǎn", meaning: "từ điển", audio: "audio/lesson3/039.mp3" },
  { hanzi: "聪明", pinyin: "cōngmíng", meaning: "thông minh", audio: "audio/lesson3/040.mp3" },

  { hanzi: "打扫", pinyin: "dǎsǎo", meaning: "dọn dẹp", audio: "audio/lesson3/041.mp3" },
  { hanzi: "打算", pinyin: "dǎsuàn", meaning: "dự định", audio: "audio/lesson3/042.mp3" },
  { hanzi: "带", pinyin: "dài", meaning: "mang theo", audio: "audio/lesson3/043.mp3" },
  { hanzi: "蛋糕", pinyin: "dàngāo", meaning: "bánh kem", audio: "audio/lesson3/044.mp3" },
  { hanzi: "担心", pinyin: "dānxīn", meaning: "lo lắng", audio: "audio/lesson3/045.mp3" },
  { hanzi: "当然", pinyin: "dāngrán", meaning: "đương nhiên", audio: "audio/lesson3/046.mp3" },
  { hanzi: "灯", pinyin: "dēng", meaning: "đèn", audio: "audio/lesson3/047.mp3" },
  { hanzi: "地", pinyin: "de", meaning: "trạng từ hóa", audio: "audio/lesson3/048.mp3" },
  { hanzi: "地方", pinyin: "dìfāng", meaning: "địa điểm", audio: "audio/lesson3/049.mp3" },
  { hanzi: "地铁", pinyin: "dìtiě", meaning: "tàu điện ngầm", audio: "audio/lesson3/050.mp3" },

  { hanzi: "地图", pinyin: "dìtú", meaning: "bản đồ", audio: "audio/lesson3/051.mp3" },
  { hanzi: "电梯", pinyin: "diàntī", meaning: "thang máy", audio: "audio/lesson3/052.mp3" },
  { hanzi: "电子邮件", pinyin: "diànzǐ yóujiàn", meaning: "email", audio: "audio/lesson3/053.mp3" },
  { hanzi: "东", pinyin: "dōng", meaning: "đông", audio: "audio/lesson3/054.mp3" },
  { hanzi: "冬", pinyin: "dōng", meaning: "mùa đông", audio: "audio/lesson3/055.mp3" },
  { hanzi: "动物", pinyin: "dòngwù", meaning: "động vật", audio: "audio/lesson3/056.mp3" },
  { hanzi: "段", pinyin: "duàn", meaning: "đoạn", audio: "audio/lesson3/057.mp3" },
  { hanzi: "短", pinyin: "duǎn", meaning: "ngắn", audio: "audio/lesson3/058.mp3" },
  { hanzi: "锻炼", pinyin: "duànliàn", meaning: "rèn luyện", audio: "audio/lesson3/059.mp3" },
  { hanzi: "多么", pinyin: "duōme", meaning: "biết bao", audio: "audio/lesson3/060.mp3" },

  { hanzi: "饿", pinyin: "è", meaning: "đói", audio: "audio/lesson3/061.mp3" },
  { hanzi: "耳朵", pinyin: "ěrduo", meaning: "tai", audio: "audio/lesson3/062.mp3" },
  { hanzi: "发", pinyin: "fā", meaning: "gửi / phát", audio: "audio/lesson3/063.mp3" },
  { hanzi: "发烧", pinyin: "fāshāo", meaning: "sốt", audio: "audio/lesson3/064.mp3" },
  { hanzi: "发现", pinyin: "fāxiàn", meaning: "phát hiện", audio: "audio/lesson3/065.mp3" },
  { hanzi: "放", pinyin: "fàng", meaning: "đặt / để", audio: "audio/lesson3/066.mp3" },
  { hanzi: "方便", pinyin: "fāngbiàn", meaning: "tiện", audio: "audio/lesson3/067.mp3" },
  { hanzi: "放心", pinyin: "fàngxīn", meaning: "yên tâm", audio: "audio/lesson3/068.mp3" },
  { hanzi: "分", pinyin: "fēn", meaning: "phút / chia", audio: "audio/lesson3/069.mp3" },
  { hanzi: "附近", pinyin: "fùjìn", meaning: "gần đây", audio: "audio/lesson3/070.mp3" },

  { hanzi: "复习", pinyin: "fùxí", meaning: "ôn tập", audio: "audio/lesson3/071.mp3" },
  { hanzi: "干净", pinyin: "gānjìng", meaning: "sạch", audio: "audio/lesson3/072.mp3" },
  { hanzi: "感冒", pinyin: "gǎnmào", meaning: "cảm cúm", audio: "audio/lesson3/073.mp3" },
  { hanzi: "感兴趣", pinyin: "gǎnxìngqù", meaning: "có hứng thú", audio: "audio/lesson3/074.mp3" },
  { hanzi: "刚才", pinyin: "gāngcái", meaning: "vừa nãy", audio: "audio/lesson3/075.mp3" },
  { hanzi: "个子", pinyin: "gèzi", meaning: "chiều cao", audio: "audio/lesson3/076.mp3" },
  { hanzi: "跟", pinyin: "gēn", meaning: "với / cùng", audio: "audio/lesson3/077.mp3" },
  { hanzi: "根据", pinyin: "gēnjù", meaning: "căn cứ", audio: "audio/lesson3/078.mp3" },
  { hanzi: "更", pinyin: "gèng", meaning: "hơn", audio: "audio/lesson3/079.mp3" },
  { hanzi: "公斤", pinyin: "gōngjīn", meaning: "kg", audio: "audio/lesson3/080.mp3" },

  { hanzi: "公园", pinyin: "gōngyuán", meaning: "công viên", audio: "audio/lesson3/081.mp3" },
  { hanzi: "故事", pinyin: "gùshi", meaning: "câu chuyện", audio: "audio/lesson3/082.mp3" },
  { hanzi: "刮风", pinyin: "guāfēng", meaning: "gió thổi", audio: "audio/lesson3/083.mp3" },
  { hanzi: "关", pinyin: "guān", meaning: "đóng", audio: "audio/lesson3/084.mp3" },
  { hanzi: "关系", pinyin: "guānxì", meaning: "quan hệ", audio: "audio/lesson3/085.mp3" },
  { hanzi: "关心", pinyin: "guānxīn", meaning: "quan tâm", audio: "audio/lesson3/086.mp3" },
  { hanzi: "关于", pinyin: "guānyú", meaning: "về", audio: "audio/lesson3/087.mp3" },
  { hanzi: "过", pinyin: "guò", meaning: "đã từng / qua", audio: "audio/lesson3/088.mp3" },
  { hanzi: "国家", pinyin: "guójiā", meaning: "quốc gia", audio: "audio/lesson3/089.mp3" },
  { hanzi: "过去", pinyin: "guòqù", meaning: "quá khứ", audio: "audio/lesson3/090.mp3" },

  { hanzi: "还", pinyin: "hái", meaning: "vẫn", audio: "audio/lesson3/091.mp3" },
  { hanzi: "害怕", pinyin: "hàipà", meaning: "sợ", audio: "audio/lesson3/092.mp3" },
  { hanzi: "还是", pinyin: "háishì", meaning: "hay là", audio: "audio/lesson3/093.mp3" },
  { hanzi: "黑板", pinyin: "hēibǎn", meaning: "bảng đen", audio: "audio/lesson3/094.mp3" },
  { hanzi: "后来", pinyin: "hòulái", meaning: "sau đó", audio: "audio/lesson3/095.mp3" },
  { hanzi: "护照", pinyin: "hùzhào", meaning: "hộ chiếu", audio: "audio/lesson3/096.mp3" },
  { hanzi: "画", pinyin: "huà", meaning: "vẽ / tranh", audio: "audio/lesson3/097.mp3" },
  { hanzi: "花", pinyin: "huā", meaning: "hoa / tiêu tiền", audio: "audio/lesson3/098.mp3" },
  { hanzi: "坏", pinyin: "huài", meaning: "hỏng / xấu", audio: "audio/lesson3/099.mp3" },
  { hanzi: "换", pinyin: "huàn", meaning: "đổi", audio: "audio/lesson3/100.mp3" },

  { hanzi: "环境", pinyin: "huánjìng", meaning: "môi trường", audio: "audio/lesson3/101.mp3" },
  { hanzi: "欢迎", pinyin: "huānyíng", meaning: "hoan nghênh", audio: "audio/lesson3/102.mp3" },
  { hanzi: "黄河", pinyin: "huánghé", meaning: "Hoàng Hà", audio: "audio/lesson3/103.mp3" },
  { hanzi: "回答", pinyin: "huídá", meaning: "trả lời", audio: "audio/lesson3/104.mp3" },
  { hanzi: "会议", pinyin: "huìyì", meaning: "hội nghị", audio: "audio/lesson3/105.mp3" },
  { hanzi: "或者", pinyin: "huòzhě", meaning: "hoặc", audio: "audio/lesson3/106.mp3" },
  { hanzi: "极", pinyin: "jí", meaning: "cực", audio: "audio/lesson3/107.mp3" },
  { hanzi: "记得", pinyin: "jìdé", meaning: "nhớ", audio: "audio/lesson3/108.mp3" },
  { hanzi: "几乎", pinyin: "jīhū", meaning: "hầu như", audio: "audio/lesson3/109.mp3" },
  { hanzi: "机会", pinyin: "jīhuì", meaning: "cơ hội", audio: "audio/lesson3/110.mp3" },

  { hanzi: "季节", pinyin: "jìjié", meaning: "mùa", audio: "audio/lesson3/111.mp3" },
  { hanzi: "检查", pinyin: "jiǎnchá", meaning: "kiểm tra", audio: "audio/lesson3/112.mp3" },
  { hanzi: "简单", pinyin: "jiǎndān", meaning: "đơn giản", audio: "audio/lesson3/113.mp3" },
  { hanzi: "健康", pinyin: "jiànkāng", meaning: "khỏe mạnh", audio: "audio/lesson3/114.mp3" },
  { hanzi: "见面", pinyin: "jiànmiàn", meaning: "gặp mặt", audio: "audio/lesson3/115.mp3" },
  { hanzi: "讲", pinyin: "jiǎng", meaning: "nói / giảng", audio: "audio/lesson3/116.mp3" },
  { hanzi: "教", pinyin: "jiào", meaning: "dạy", audio: "audio/lesson3/117.mp3" },
  { hanzi: "脚", pinyin: "jiǎo", meaning: "chân", audio: "audio/lesson3/118.mp3" },
  { hanzi: "角", pinyin: "jiǎo", meaning: "góc / tiền lẻ", audio: "audio/lesson3/119.mp3" },
  { hanzi: "借", pinyin: "jiè", meaning: "mượn", audio: "audio/lesson3/120.mp3" },

  { hanzi: "接", pinyin: "jiē", meaning: "đón / nhận", audio: "audio/lesson3/121.mp3" },
  { hanzi: "街道", pinyin: "jiēdào", meaning: "đường phố", audio: "audio/lesson3/122.mp3" },
  { hanzi: "结婚", pinyin: "jiéhūn", meaning: "kết hôn", audio: "audio/lesson3/123.mp3" },
  { hanzi: "解决", pinyin: "jiějué", meaning: "giải quyết", audio: "audio/lesson3/124.mp3" },
  { hanzi: "节目", pinyin: "jiémù", meaning: "chương trình", audio: "audio/lesson3/125.mp3" },
  { hanzi: "节日", pinyin: "jiérì", meaning: "lễ hội", audio: "audio/lesson3/126.mp3" },
  { hanzi: "结束", pinyin: "jiéshù", meaning: "kết thúc", audio: "audio/lesson3/127.mp3" },
  { hanzi: "经常", pinyin: "jīngcháng", meaning: "thường xuyên", audio: "audio/lesson3/128.mp3" },
  { hanzi: "经过", pinyin: "jīngguò", meaning: "đi qua", audio: "audio/lesson3/129.mp3" },
  { hanzi: "经理", pinyin: "jīnglǐ", meaning: "giám đốc", audio: "audio/lesson3/130.mp3" },

  { hanzi: "旧", pinyin: "jiù", meaning: "cũ", audio: "audio/lesson3/131.mp3" },
  { hanzi: "久", pinyin: "jiǔ", meaning: "lâu", audio: "audio/lesson3/132.mp3" },
  { hanzi: "句子", pinyin: "jùzi", meaning: "câu", audio: "audio/lesson3/133.mp3" },
  { hanzi: "决定", pinyin: "juédìng", meaning: "quyết định", audio: "audio/lesson3/134.mp3" },
  { hanzi: "刻", pinyin: "kè", meaning: "15 phút", audio: "audio/lesson3/135.mp3" },
  { hanzi: "渴", pinyin: "kě", meaning: "khát", audio: "audio/lesson3/136.mp3" },
  { hanzi: "可爱", pinyin: "kěài", meaning: "đáng yêu", audio: "audio/lesson3/137.mp3" },
  { hanzi: "客人", pinyin: "kèrén", meaning: "khách", audio: "audio/lesson3/138.mp3" },
  { hanzi: "空调", pinyin: "kōngtiáo", meaning: "điều hòa", audio: "audio/lesson3/139.mp3" },
  { hanzi: "口", pinyin: "kǒu", meaning: "miệng", audio: "audio/lesson3/140.mp3" },

  { hanzi: "哭", pinyin: "kū", meaning: "khóc", audio: "audio/lesson3/141.mp3" },
  { hanzi: "裤子", pinyin: "kùzi", meaning: "quần", audio: "audio/lesson3/142.mp3" },
  { hanzi: "筷子", pinyin: "kuàizi", meaning: "đũa", audio: "audio/lesson3/143.mp3" },
  { hanzi: "蓝", pinyin: "lán", meaning: "xanh lam", audio: "audio/lesson3/144.mp3" },
  { hanzi: "老", pinyin: "lǎo", meaning: "già / cũ", audio: "audio/lesson3/145.mp3" },
  { hanzi: "离开", pinyin: "líkāi", meaning: "rời đi", audio: "audio/lesson3/146.mp3" },
  { hanzi: "历史", pinyin: "lìshǐ", meaning: "lịch sử", audio: "audio/lesson3/147.mp3" },
  { hanzi: "礼物", pinyin: "lǐwù", meaning: "quà", audio: "audio/lesson3/148.mp3" },
  { hanzi: "脸", pinyin: "liǎn", meaning: "mặt", audio: "audio/lesson3/149.mp3" },
  { hanzi: "练习", pinyin: "liànxí", meaning: "luyện tập", audio: "audio/lesson3/150.mp3" },

  { hanzi: "辆", pinyin: "liàng", meaning: "lượng từ xe", audio: "audio/lesson3/151.mp3" },
  { hanzi: "了解", pinyin: "liǎojiě", meaning: "hiểu", audio: "audio/lesson3/152.mp3" },
  { hanzi: "聊天", pinyin: "liáotiān", meaning: "chat", audio: "audio/lesson3/153.mp3" },
  { hanzi: "邻居", pinyin: "línjū", meaning: "hàng xóm", audio: "audio/lesson3/154.mp3" },
  { hanzi: "留学", pinyin: "liúxué", meaning: "du học", audio: "audio/lesson3/155.mp3" },
  { hanzi: "楼", pinyin: "lóu", meaning: "tầng / nhà cao tầng", audio: "audio/lesson3/156.mp3" },
  { hanzi: "绿", pinyin: "lǜ", meaning: "xanh lá", audio: "audio/lesson3/157.mp3" },
  { hanzi: "马", pinyin: "mǎ", meaning: "ngựa", audio: "audio/lesson3/158.mp3" },
  { hanzi: "马上", pinyin: "mǎshàng", meaning: "ngay lập tức", audio: "audio/lesson3/159.mp3" },
  { hanzi: "满意", pinyin: "mǎnyì", meaning: "hài lòng", audio: "audio/lesson3/160.mp3" },
  { hanzi: "帽子", pinyin: "màozi", meaning: "mũ", audio: "audio/lesson3/161.mp3" },
  { hanzi: "米", pinyin: "mǐ", meaning: "gạo / mét", audio: "audio/lesson3/162.mp3" },
  { hanzi: "面包", pinyin: "miànbāo", meaning: "bánh mì", audio: "audio/lesson3/163.mp3" },
  { hanzi: "明白", pinyin: "míngbái", meaning: "hiểu rõ", audio: "audio/lesson3/164.mp3" },
  { hanzi: "拿", pinyin: "ná", meaning: "cầm / lấy", audio: "audio/lesson3/165.mp3" },
  { hanzi: "奶奶", pinyin: "nǎinai", meaning: "bà nội", audio: "audio/lesson3/166.mp3" },
  { hanzi: "南", pinyin: "nán", meaning: "nam", audio: "audio/lesson3/167.mp3" },
  { hanzi: "难", pinyin: "nán", meaning: "khó", audio: "audio/lesson3/168.mp3" },
  { hanzi: "难过", pinyin: "nánguò", meaning: "buồn", audio: "audio/lesson3/169.mp3" },
  { hanzi: "年级", pinyin: "niánjí", meaning: "khối / lớp", audio: "audio/lesson3/170.mp3" },

  { hanzi: "年轻", pinyin: "niánqīng", meaning: "trẻ", audio: "audio/lesson3/171.mp3" },
  { hanzi: "鸟", pinyin: "niǎo", meaning: "chim", audio: "audio/lesson3/172.mp3" },
  { hanzi: "努力", pinyin: "nǔlì", meaning: "cố gắng", audio: "audio/lesson3/173.mp3" },
  { hanzi: "爬山", pinyin: "páshān", meaning: "leo núi", audio: "audio/lesson3/174.mp3" },
  { hanzi: "盘子", pinyin: "pánzi", meaning: "đĩa", audio: "audio/lesson3/175.mp3" },
  { hanzi: "胖", pinyin: "pàng", meaning: "béo", audio: "audio/lesson3/176.mp3" },
  { hanzi: "啤酒", pinyin: "píjiǔ", meaning: "bia", audio: "audio/lesson3/177.mp3" },
  { hanzi: "皮鞋", pinyin: "píxié", meaning: "giày da", audio: "audio/lesson3/178.mp3" },
  { hanzi: "瓶子", pinyin: "píngzi", meaning: "chai", audio: "audio/lesson3/179.mp3" },
  { hanzi: "骑", pinyin: "qí", meaning: "cưỡi / đi xe", audio: "audio/lesson3/180.mp3" },

  { hanzi: "起飞", pinyin: "qǐfēi", meaning: "cất cánh", audio: "audio/lesson3/181.mp3" },
  { hanzi: "奇怪", pinyin: "qíguài", meaning: "kỳ lạ", audio: "audio/lesson3/182.mp3" },
  { hanzi: "起来", pinyin: "qǐlái", meaning: "dậy / đứng lên", audio: "audio/lesson3/183.mp3" },
  { hanzi: "其实", pinyin: "qíshí", meaning: "thực ra", audio: "audio/lesson3/184.mp3" },
  { hanzi: "其他", pinyin: "qítā", meaning: "khác", audio: "audio/lesson3/185.mp3" },
  { hanzi: "清楚", pinyin: "qīngchǔ", meaning: "rõ ràng", audio: "audio/lesson3/186.mp3" },
  { hanzi: "请假", pinyin: "qǐngjià", meaning: "xin nghỉ", audio: "audio/lesson3/187.mp3" },
  { hanzi: "秋", pinyin: "qiū", meaning: "mùa thu", audio: "audio/lesson3/188.mp3" },
  { hanzi: "裙子", pinyin: "qúnzi", meaning: "váy", audio: "audio/lesson3/189.mp3" },
  { hanzi: "然后", pinyin: "ránhòu", meaning: "sau đó", audio: "audio/lesson3/190.mp3" },

  { hanzi: "热情", pinyin: "rèqíng", meaning: "nhiệt tình", audio: "audio/lesson3/191.mp3" },
  { hanzi: "认为", pinyin: "rènwéi", meaning: "cho rằng", audio: "audio/lesson3/192.mp3" },
  { hanzi: "认真", pinyin: "rènzhēn", meaning: "chăm chỉ / nghiêm túc", audio: "audio/lesson3/193.mp3" },
  { hanzi: "容易", pinyin: "róngyì", meaning: "dễ", audio: "audio/lesson3/194.mp3" },
  { hanzi: "如果", pinyin: "rúguǒ", meaning: "nếu", audio: "audio/lesson3/195.mp3" },
  { hanzi: "伞", pinyin: "sǎn", meaning: "ô / dù", audio: "audio/lesson3/196.mp3" },
  { hanzi: "上网", pinyin: "shàngwǎng", meaning: "lên mạng", audio: "audio/lesson3/197.mp3" },
  { hanzi: "生气", pinyin: "shēngqì", meaning: "tức giận", audio: "audio/lesson3/198.mp3" },
  { hanzi: "声音", pinyin: "shēngyīn", meaning: "âm thanh", audio: "audio/lesson3/199.mp3" },
  { hanzi: "试", pinyin: "shì", meaning: "thử", audio: "audio/lesson3/200.mp3" },

  { hanzi: "世界", pinyin: "shìjiè", meaning: "thế giới", audio: "audio/lesson3/201.mp3" },
  { hanzi: "瘦", pinyin: "shòu", meaning: "gầy", audio: "audio/lesson3/202.mp3" },
  { hanzi: "树", pinyin: "shù", meaning: "cây", audio: "audio/lesson3/203.mp3" },
  { hanzi: "舒服", pinyin: "shūfu", meaning: "thoải mái", audio: "audio/lesson3/204.mp3" },
  { hanzi: "叔叔", pinyin: "shūshu", meaning: "chú", audio: "audio/lesson3/205.mp3" },
  { hanzi: "数学", pinyin: "shùxué", meaning: "toán học", audio: "audio/lesson3/206.mp3" },
  { hanzi: "刷牙", pinyin: "shuāyá", meaning: "đánh răng", audio: "audio/lesson3/207.mp3" },
  { hanzi: "双", pinyin: "shuāng", meaning: "đôi", audio: "audio/lesson3/208.mp3" },
  { hanzi: "水平", pinyin: "shuǐpíng", meaning: "trình độ", audio: "audio/lesson3/209.mp3" },
  { hanzi: "司机", pinyin: "sījī", meaning: "tài xế", audio: "audio/lesson3/210.mp3" },

  { hanzi: "太阳", pinyin: "tàiyáng", meaning: "mặt trời", audio: "audio/lesson3/211.mp3" },
  { hanzi: "特别", pinyin: "tèbié", meaning: "đặc biệt", audio: "audio/lesson3/212.mp3" },
  { hanzi: "疼", pinyin: "téng", meaning: "đau", audio: "audio/lesson3/213.mp3" },
  { hanzi: "提高", pinyin: "tígāo", meaning: "nâng cao", audio: "audio/lesson3/214.mp3" },
  { hanzi: "体育", pinyin: "tǐyù", meaning: "thể thao", audio: "audio/lesson3/215.mp3" },
  { hanzi: "甜", pinyin: "tián", meaning: "ngọt", audio: "audio/lesson3/216.mp3" },
  { hanzi: "条", pinyin: "tiáo", meaning: "lượng từ (cái)", audio: "audio/lesson3/217.mp3" },
  { hanzi: "同事", pinyin: "tóngshì", meaning: "đồng nghiệp", audio: "audio/lesson3/218.mp3" },
  { hanzi: "同意", pinyin: "tóngyì", meaning: "đồng ý", audio: "audio/lesson3/219.mp3" },
  { hanzi: "头发", pinyin: "tóufà", meaning: "tóc", audio: "audio/lesson3/220.mp3" },

  { hanzi: "突然", pinyin: "tūrán", meaning: "đột nhiên", audio: "audio/lesson3/221.mp3" },
  { hanzi: "图书馆", pinyin: "túshūguǎn", meaning: "thư viện", audio: "audio/lesson3/222.mp3" },
  { hanzi: "腿", pinyin: "tuǐ", meaning: "chân", audio: "audio/lesson3/223.mp3" },
  { hanzi: "万", pinyin: "wàn", meaning: "vạn", audio: "audio/lesson3/224.mp3" },
  { hanzi: "碗", pinyin: "wǎn", meaning: "bát", audio: "audio/lesson3/225.mp3" },
  { hanzi: "完成", pinyin: "wánchéng", meaning: "hoàn thành", audio: "audio/lesson3/226.mp3" },
  { hanzi: "忘记", pinyin: "wàngjì", meaning: "quên", audio: "audio/lesson3/227.mp3" },
  { hanzi: "为", pinyin: "wèi", meaning: "vì", audio: "audio/lesson3/228.mp3" },
  { hanzi: "位", pinyin: "wèi", meaning: "lượng từ (vị)", audio: "audio/lesson3/229.mp3" },
  { hanzi: "为了", pinyin: "wèile", meaning: "để / vì", audio: "audio/lesson3/230.mp3" },

  { hanzi: "文化", pinyin: "wénhuà", meaning: "văn hóa", audio: "audio/lesson3/231.mp3" },
  { hanzi: "西", pinyin: "xī", meaning: "tây", audio: "audio/lesson3/232.mp3" },
  { hanzi: "习惯", pinyin: "xíguàn", meaning: "thói quen", audio: "audio/lesson3/233.mp3" },
  { hanzi: "洗手间", pinyin: "xǐshǒujiān", meaning: "nhà vệ sinh", audio: "audio/lesson3/234.mp3" },
  { hanzi: "洗澡", pinyin: "xǐzǎo", meaning: "tắm", audio: "audio/lesson3/235.mp3" },
  { hanzi: "夏", pinyin: "xià", meaning: "mùa hè", audio: "audio/lesson3/236.mp3" },
  { hanzi: "先", pinyin: "xiān", meaning: "trước", audio: "audio/lesson3/237.mp3" },
  { hanzi: "像", pinyin: "xiàng", meaning: "giống", audio: "audio/lesson3/238.mp3" },
  { hanzi: "向", pinyin: "xiàng", meaning: "hướng về", audio: "audio/lesson3/239.mp3" },
  { hanzi: "香蕉", pinyin: "xiāngjiāo", meaning: "chuối", audio: "audio/lesson3/240.mp3" },

  { hanzi: "相信", pinyin: "xiāngxìn", meaning: "tin tưởng", audio: "audio/lesson3/241.mp3" },
  { hanzi: "小心", pinyin: "xiǎoxīn", meaning: "cẩn thận", audio: "audio/lesson3/242.mp3" },
  { hanzi: "校长", pinyin: "xiàozhǎng", meaning: "hiệu trưởng", audio: "audio/lesson3/243.mp3" },
  { hanzi: "新闻", pinyin: "xīnwén", meaning: "tin tức", audio: "audio/lesson3/244.mp3" },
  { hanzi: "新鲜", pinyin: "xīnxiān", meaning: "tươi", audio: "audio/lesson3/245.mp3" },
  { hanzi: "信用卡", pinyin: "xìnyòngkǎ", meaning: "thẻ tín dụng", audio: "audio/lesson3/246.mp3" },
  { hanzi: "行李箱", pinyin: "xínglǐxiāng", meaning: "vali", audio: "audio/lesson3/247.mp3" },
  { hanzi: "熊猫", pinyin: "xióngmāo", meaning: "gấu trúc", audio: "audio/lesson3/248.mp3" },
  { hanzi: "需要", pinyin: "xūyào", meaning: "cần", audio: "audio/lesson3/249.mp3" },
  { hanzi: "选择", pinyin: "xuǎnzé", meaning: "lựa chọn", audio: "audio/lesson3/250.mp3" },

  { hanzi: "要求", pinyin: "yāoqiú", meaning: "yêu cầu", audio: "audio/lesson3/251.mp3" },
  { hanzi: "爷爷", pinyin: "yéye", meaning: "ông nội", audio: "audio/lesson3/252.mp3" },
  { hanzi: "一般", pinyin: "yībān", meaning: "bình thường", audio: "audio/lesson3/253.mp3" },
  { hanzi: "一边", pinyin: "yībiān", meaning: "vừa… vừa…", audio: "audio/lesson3/254.mp3" },
  { hanzi: "一定", pinyin: "yīdìng", meaning: "nhất định", audio: "audio/lesson3/255.mp3" },
  { hanzi: "一共", pinyin: "yīgòng", meaning: "tổng cộng", audio: "audio/lesson3/256.mp3" },
  { hanzi: "一会儿", pinyin: "yíhuìr", meaning: "một lúc", audio: "audio/lesson3/257.mp3" },
  { hanzi: "以前", pinyin: "yǐqián", meaning: "trước đây", audio: "audio/lesson3/258.mp3" },
  { hanzi: "一样", pinyin: "yíyàng", meaning: "giống nhau", audio: "audio/lesson3/259.mp3" },
  { hanzi: "一直", pinyin: "yìzhí", meaning: "liên tục", audio: "audio/lesson3/260.mp3" },

  { hanzi: "银行", pinyin: "yínháng", meaning: "ngân hàng", audio: "audio/lesson3/261.mp3" },
  { hanzi: "饮料", pinyin: "yǐnliào", meaning: "đồ uống", audio: "audio/lesson3/262.mp3" },
  { hanzi: "音乐", pinyin: "yīnyuè", meaning: "âm nhạc", audio: "audio/lesson3/263.mp3" },
  { hanzi: "应该", pinyin: "yīnggāi", meaning: "nên", audio: "audio/lesson3/264.mp3" },
  { hanzi: "影响", pinyin: "yǐngxiǎng", meaning: "ảnh hưởng", audio: "audio/lesson3/265.mp3" },
  { hanzi: "用", pinyin: "yòng", meaning: "dùng", audio: "audio/lesson3/266.mp3" },
  { hanzi: "又", pinyin: "yòu", meaning: "lại", audio: "audio/lesson3/267.mp3" },
  { hanzi: "有名", pinyin: "yǒumíng", meaning: "nổi tiếng", audio: "audio/lesson3/268.mp3" },
  { hanzi: "游戏", pinyin: "yóuxì", meaning: "trò chơi", audio: "audio/lesson3/269.mp3" },
  { hanzi: "遇到", pinyin: "yùdào", meaning: "gặp", audio: "audio/lesson3/270.mp3" },

  { hanzi: "元", pinyin: "yuán", meaning: "tệ / đồng", audio: "audio/lesson3/271.mp3" },
  { hanzi: "愿意", pinyin: "yuànyì", meaning: "sẵn lòng", audio: "audio/lesson3/272.mp3" },
  { hanzi: "越", pinyin: "yuè", meaning: "càng", audio: "audio/lesson3/273.mp3" },
  { hanzi: "月亮", pinyin: "yuèliàng", meaning: "mặt trăng", audio: "audio/lesson3/274.mp3" },
  { hanzi: "站", pinyin: "zhàn", meaning: "trạm", audio: "audio/lesson3/275.mp3" },
  { hanzi: "张", pinyin: "zhāng", meaning: "lượng từ tờ", audio: "audio/lesson3/276.mp3" },
  { hanzi: "长", pinyin: "zhǎng", meaning: "lớn / trưởng thành", audio: "audio/lesson3/277.mp3" },
  { hanzi: "照顾", pinyin: "zhàogù", meaning: "chăm sóc", audio: "audio/lesson3/278.mp3" },
  { hanzi: "着急", pinyin: "zhāojí", meaning: "sốt ruột", audio: "audio/lesson3/279.mp3" },
  { hanzi: "照片", pinyin: "zhàopiàn", meaning: "ảnh", audio: "audio/lesson3/280.mp3" },

  { hanzi: "照相机", pinyin: "zhàoxiàngjī", meaning: "máy ảnh", audio: "audio/lesson3/281.mp3" },
  { hanzi: "只", pinyin: "zhī", meaning: "chỉ / con (lượng từ)", audio: "audio/lesson3/282.mp3" },
  { hanzi: "只", pinyin: "zhī", meaning: "chỉ", audio: "audio/lesson3/283.mp3" },
  { hanzi: "只有…才…", pinyin: "zhǐyǒu… cái…", meaning: "chỉ khi… mới…", audio: "audio/lesson3/284.mp3" },
  { hanzi: "种", pinyin: "zhǒng", meaning: "loại", audio: "audio/lesson3/285.mp3" },
  { hanzi: "中间", pinyin: "zhōngjiān", meaning: "ở giữa", audio: "audio/lesson3/286.mp3" },
  { hanzi: "中文", pinyin: "zhōngwén", meaning: "tiếng Trung", audio: "audio/lesson3/287.mp3" },
  { hanzi: "重要", pinyin: "zhòngyào", meaning: "quan trọng", audio: "audio/lesson3/288.mp3" },
  { hanzi: "终于", pinyin: "zhōngyú", meaning: "cuối cùng", audio: "audio/lesson3/289.mp3" },
  { hanzi: "周末", pinyin: "zhōumò", meaning: "cuối tuần", audio: "audio/lesson3/290.mp3" },

  { hanzi: "主要", pinyin: "zhǔyào", meaning: "chủ yếu", audio: "audio/lesson3/291.mp3" },
  { hanzi: "注意", pinyin: "zhùyì", meaning: "chú ý", audio: "audio/lesson3/292.mp3" },
  { hanzi: "自己", pinyin: "zìjǐ", meaning: "bản thân", audio: "audio/lesson3/293.mp3" },
  { hanzi: "自行车", pinyin: "zìxíngchē", meaning: "xe đạp", audio: "audio/lesson3/294.mp3" },
  { hanzi: "总是", pinyin: "zǒngshì", meaning: "luôn luôn", audio: "audio/lesson3/295.mp3" },
  { hanzi: "嘴", pinyin: "zuǐ", meaning: "miệng", audio: "audio/lesson3/296.mp3" },
  { hanzi: "最后", pinyin: "zuìhòu", meaning: "cuối cùng", audio: "audio/lesson3/297.mp3" },
  { hanzi: "最近", pinyin: "zuìjìn", meaning: "gần đây", audio: "audio/lesson3/298.mp3" },
  { hanzi: "作业", pinyin: "zuòyè", meaning: "bài tập", audio: "audio/lesson3/299.mp3" },
  { hanzi: "结束", pinyin: "jiéshù", meaning: "kết thúc", audio: "audio/lesson3/300.mp3" }
];